# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muya', '0002_auto_20180328_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('question_Feedback', models.CharField(max_length=1000)),
            ],
        ),
    ]
