# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('muya', '0003_feedbackrecipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField(null=True)),
                ('Question_or_Feedback', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackRecipients',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
