# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muya', '0004_auto_20180822_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Phone_Number',
        ),
    ]
